
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/influxdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - image: influxdb-alpine
        name: influxdb-alpine
        imagePullPolicy: Never
        ports:
        - name: http 
          containerPort: 8086
        volumeMounts:
          - name: influxdb-persistent-volume 
            mountPath: /var/lib/influxdb/
      volumes:
       - name: influxdb-persistent-volume
         persistentVolumeClaim:
          claimName: influxdb-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  type: ClusterIP
  ports:
  - port: 8086
    targetPort: http
  selector:
    app: influxdb