apiVersion: v1
kind: PersistentVolume
metadata:
  name: telegraf-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/telegraf"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telegraf-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - image: telegraf-alpine
        name: telegraf-alpine
        imagePullPolicy: Never
        ports:
        - containerPort: 8125 
        volumeMounts:
        - name: telegraf-endpoint
          mountPath: "/var/run/docker.sock"
      volumes:
      - name: telegraf-endpoint
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
spec:
  type: ClusterIP
  ports:
  - port: 8125
    targetPort: http
  selector:
    app: telegraf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf
  labels:
    app: telegraf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: telegraf
  namespace: default